### ISSUE TITLE
[feat] 금융 상품 검색 기능 구현

### ISSUE THREAD

**Issue by jisoooit** [Financial-Instruments-Mini/Project_BE#27]
## Description (설명)

금융 상품 검색 기능을 구현한다.

## Tasks(New feature)

- [ ] 금융 상품 검색 관련 dto 생성
- [ ] 카테고리에 따른 상품 검색 
- [ ] 정렬기준에 따른 상품 검색
- [ ] 검색 테스트

## References
[link text]()
